---
tags:
- pdep
- guia1
- basico
- aritmetica
- operadoresLogicos
- composicion
- aplicationParcial
layout: input_right
editor: code
type: problem
extra_visible: false
language: 
teacher_info: 
manual_evaluation: false
choices: []
